name: 'Crayceratops Azure Resources'
on: [push]
jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout Crayceratops Resources repository'
        uses: 'actions/checkout@v2'
        with:
          clean: true
          fetch-depth: 1
          lfs: false
          path: ${{ format('{0}/project', github.workspace) }}
          submodules: false
      - name: 'login to Azure'
        uses: 'azure/login@v1'
        with:
          allow-no-subscriptions: true
          creds: ${{ secrets.AZURE_APPLICATION_CREDENTIALS }}
          environment: 'AzureCloud'
      - name: 'deploy template to Azure Resource Group'
        run: |
          $deploymentMode = 'Incremental';
          $deploymentName = ${{ format('''{0}.{1}''', hashFiles(format('{0}/project/Azure.Resources.json', github.workspace)), github.run_number) }};
          $parametersFilePath = ${{ format('''{0}/project/Azure.Resources.json''', github.workspace) }};
          $resourceGroupName = 'crayceratops';
          $subscriptionIdOrName = 'byteterrace-mpn';
          $templateSpecName = 'ResourceGroupDeployment';
          $templateSpecResourceGroupName = 'byteterrace';
          $templateSpecSubscriptionNameOrId = 'byteterrace-mpn';
          $templateSpecVersion = 'latest';

          $deploymentName = $deploymentName.Substring(48);

          if ([string]::IsNullOrEmpty($templateSpecVersion) -or ('latest' -eq $templateSpecVersion)) {
              $templateSpecId = (az ts list `
                  --name $templateSpecName `
                  --query 'reverse(sort_by([], &name))[0].id' `
                  --resource-group $templateSpecResourceGroupName `
                  --subscription $templateSpecSubscriptionNameOrId | ConvertFrom-Json);
          }
          else {
              $templateSpecId = (az ts show `
                  --name $templateSpecName `
                  --query 'id' `
                  --resource-group $templateSpecResourceGroupName `
                  --subscription $templateSpecSubscriptionNameOrId `
                  --version $templateSpecVersion);
          }

          az deployment group create `
              --mode $deploymentMode `
              --name $deploymentName `
              --parameters ('@{0}' -f $parametersFilePath) `
              --resource-group $resourceGroupName `
              --subscription $subscriptionIdOrName `
              --template-spec $templateSpecId;
        shell: 'pwsh'
      - name: 'logout of Azure'
        uses: 'azure/CLI@v1'
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear
